FROM node:22-alpine AS builder
WORKDIR /app
COPY frontend/user-app/package*.json ./
RUN npm ci
COPY frontend/user-app/ .
RUN sh node_modules/.bin/vue-tsc -b && sh node_modules/.bin/vite build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
